name: Run Program on Push

on:
  push:
    branches:
      - main
  schedule:
    - cron: '01 21 * * *'  # 台灣時間 05:01
    - cron: '11 6 * * *'   # 台灣時間 14:11

jobs:
  run_program:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Clean pip cache and reinstall
        run: |
          python -m pip install --upgrade pip
          pip cache purge || true
          pip uninstall -y firebase-admin google-cloud-firestore packaging google-api-core || true
          pip install --no-cache-dir packaging google-api-core firebase-admin==6.5.0 google-cloud-firestore==2.17.0 yfinance

      - name: Verify installation
        run: |
          python -m pip show firebase-admin
          python -m pip show google-cloud-firestore
          python -m pip show packaging
          python -m pip show yfinance

      - name: Run your program
        env:
          FIREBASE: ${{ secrets.FIREBASE }}
        run: |
          python FireBase.py
